# Generated by Django 4.1.7 on 2023-03-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imagens', verbose_name='Imagem'),
        ),
    ]
